FROM node:20-slim
WORKDIR /app

RUN apt-get update -y && apt-get install -y openssl

COPY . .

COPY .env.docker.prod .env

RUN npm install
RUN npm run build
RUN npm prune --production

EXPOSE 3000

CMD node scripts/sync-daemon.cjs & npm run start

