FROM node:20-slim
WORKDIR /app

RUN apt-get update -y && apt-get install -y openssl tzdata

ENV TZ=America/Sao_Paulo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY . .

COPY .env.docker.prod .env

RUN npm install
RUN npm run build
RUN npm prune --production

EXPOSE 3000

CMD node --env-file=.env scripts/sync-daemon.cjs & node .next/standalone/server.js

